"""
Django settings for rummi project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
restart:
kill process /usr/local/bin/uwsgi --emperor and restart
sudo /usr/local/bin/uwsgi --emperor /etc/uwsgi/vassals --uid nginx --gid nginx --daemonize /var/log/uwsgi-emperor.log

projectName="rummi"
sudo ln -s /var/data/python/django/$projectName/$projectName_uwsgi.ini /etc/uwsgi/vassals/
cp ../polla3dm/uwsgi_params .
. ../projectenv/bin/activate
python manage.py migrate
python manage.py createsuperuser
python manage.py collectstatic

"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+#vef!#q_^*%a5cdew@1!e(dt^00m#sw4ckcghci@bmmibnb&j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['rummi.servoz.tk', '127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rummiApp.apps.rummiAppConfig',
    'django_extensions',
    'translation_manager',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'rummi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rummi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'rummi',
        'HOST': '127.0.0.1',
        'USER': 'rummi_usr',
        'PASSWORD': '3x1Fkx6UtNM1ED7d)sZvo&Y0se%'
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

DJANGO_LOG_LEVEL = DEBUG

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR+'/rummiApp/logs/debug.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
        'django.server': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        }
    }
}


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_L10N = False

USE_TZ = True

DATETIME_FORMAT = 'Y-m-d H:i:s'

LOCALE_PATHS = [
    BASE_DIR+'/locale/',
]
TRANSLATIONS_BASE_DIR = ''
TRANSLATIONS_PROJECT_BASE_DIR = BASE_DIR
TRANSLATIONS_SYNC_REMOTE_URL = ''


FROMEMAIL = 'no-reply@servoz.tk'
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_HOST_USER = 'no-reply@servoz.tk'
# EMAIL_HOST_PASSWORD = '$af4VAYU1ER-3%!'
# EMAIL_USE_TLS = True
# DEFAULT_FROM_EMAIL = 'Rummi App <info@servoz.tk>'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
LOGIN_URL = '/login/'
LOGOUT_URL = '/'
ADMIN_URL = 'AdminRummi/'
LOGIN_REDIRECT_URL = '/'+ADMIN_URL
LANGUAGES = (('en', 'English'), ('es', 'Español'))
LOGPATH = BASE_DIR + 'rummiApp/logs/'

AUTH_PASSWORD_VALIDATORS = []
