# Generated by Django 3.0.6 on 2020-05-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rummiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tmpPIN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150)),
                ('pin', models.CharField(max_length=6)),
            ],
        ),
    ]
