# Generated by Django 3.0.6 on 2020-05-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rummiApp', '0004_auto_20200517_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameset',
            name='currentPlayer',
            field=models.IntegerField(default=0),
        ),
    ]
