# Generated by Django 3.0.6 on 2020-05-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rummiApp', '0005_gameset_currentplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameset',
            name='playersPos',
            field=models.CharField(default='', max_length=100),
        ),
    ]
