# Generated by Django 3.0.6 on 2020-05-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rummiApp', '0006_gameset_playerspos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameset',
            name='currentPlayer',
        ),
        migrations.RemoveField(
            model_name='gameset',
            name='playersPos',
        ),
        migrations.AddField(
            model_name='game',
            name='currentPlayerPos',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='playersPos',
            field=models.CharField(default=',,,,', max_length=100),
        ),
    ]
