# Generated by Django 3.0.6 on 2020-05-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rummiApp', '0008_game_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_discarted',
            field=models.CharField(default='|||', max_length=500),
        ),
    ]
