# Generated by Django 3.0.6 on 2020-05-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rummiApp', '0011_auto_20200519_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameset',
            name='chairPos',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='gameset',
            unique_together={('playerId', 'gameId', 'set', 'chairPos')},
        ),
    ]
