# Generated by Django 3.0.6 on 2020-05-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rummiApp', '0012_auto_20200519_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameset',
            name='moveStatus',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='current_discarted',
            field=models.CharField(default='||||', max_length=500),
        ),
    ]
