# Generated by Django 3.0.6 on 2020-05-20 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rummiApp', '0013_auto_20200520_0736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='current_discarted',
            new_name='current_discarded',
        ),
    ]
