# Generated by Django 3.0.6 on 2020-05-31 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rummiApp', '0014_auto_20200520_0802'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameset',
            unique_together={('playerId', 'gameId', 'set')},
        ),
        migrations.AlterUniqueTogether(
            name='tmppin',
            unique_together={('email', 'pin')},
        ),
        migrations.RemoveField(
            model_name='gameset',
            name='chairPos',
        ),
    ]
